### ISSUE TITLE
Validate ORCIDs in codecheck.yml

### ISSUE THREAD

**Issue by nuest** [codecheckers/codecheck#11]
Only existing ORCIDs should be used.

```r
rorcid::orcid_id(orcid = "0000-0002-9341-7985")
# should not be empty
```

Also, we can point to [`rorcid` package](https://docs.ropensci.org/rorcid/reference/index.html) in the documentaiton, which might streamline lookup of ORCIDs for names. Note when I tried this in a container, the callback for the authentication did not work :-/.

Also add `rorcid` to `Suggests` in the `DESCRIPTION` file.

**Comment by sje30** [comment]
https://stackoverflow.com/questions/3262569/validating-a-yaml-document-in-python for validating more generally.

**Comment by nuest** [comment]
Re. general YAML valiation, the R `yaml` package does not seem to have that feature yet: https://github.com/viking/r-yaml/issues/19 However, since we parse the yaml file, we should test if the parsing catches generic errors.

**Comment by nuest** [comment]
`rorcid::orcid_id` requires authentication to access the ORCID API.

**Comment by nuest** [comment]
```r
> httr::GET("https://orcid.org/0000-0002-9341-7985")$status
[1] 200
> httr::GET("https://orcid.org/0000-not-an-orcid")$status
[1] 200
> httr::GET("https://orcid.org/0000-not-an-orcid")
Response [https://orcid.org/signin]
  Date: 2020-09-02 08:31
  Status: 200
  Content-Type: text/html;charset=UTF-8
[...]
```

Even the HTTP request requires login.

**Comment by nuest** [comment]
See also https://github.com/MangoTheCat/goodpractice/issues/111 - maybe they come up with a solution.

**Comment by nuest** [comment]
A regex - based validation happens with #18 - for everything else we need API access, which I'd say is too much right now.

**Comment by sckott** [comment]
sorry to just drop in here but I stumbled upon this - i'm the rorcid maintainer. seems like a use case that should be possible to check that an ORCID is valid without requiring auth. a head request seems to work without auth:

```
# real orcid
curl -IL -s -o /dev/null -w "%{http_code}" https://pub.orcid.org/v3.0/0000-0002-9341-7985/person
200

# not real orcid
curl -IL -s -o /dev/null -w "%{http_code}" https://pub.orcid.org/v3.0/0000-0002-9341-7985234234/person
404
```

Also curious why can't you use your own personal auth for this? Would each user need to use their own auth or could you use your auth for everyone?
