### ISSUE TITLE
Manifest table overflows

### ISSUE THREAD

**Issue by nuest** [codecheckers/codecheck#12]
![image](https://user-images.githubusercontent.com/1325054/82474745-cf966500-9acb-11ea-8023-432abfe19c92.png)

**Comment by sje30** [comment]
good catch.  Is your report still in progress?  we could make the 2nd column something ilke 
    p{15cm}

does that fix it?

**Comment by sje30** [comment]
@nuest These should now be fixed in the current version of the package.  See new function
`latex-summary_of_manifest`
