### ISSUE TITLE
rename citation()

### ISSUE THREAD

**Issue by sje30** [codecheckers/codecheck#16]
Currently `citation()` generates a citation of the current codecheck certificate.  the function name clashes though with base::citation() which should be left alone.  (incidentally, `citation("codecheck")` is already half-usable.)

should we simply not export the function, and rely on `codecheck:::citation()` or rename the function to something like `codecheck_cite_cert()`  or `cite_certificate()`?  My preference would be option 3.

**Comment by nuest** [comment]
`cite_certificate()` sounds good!

`codecheck_cite_cert()` only if we start prepending `codecheck_` to all functions. Or `cdchck_`. But I don't have a strong opinion on that.
