### ISSUE TITLE
Make package >= R 4.0

### ISSUE THREAD

**Issue by nuest** [codecheckers/codecheck#2]
This tweet https://twitter.com/daranzolin/status/1254486875303075841/photo/1

![image](https://user-images.githubusercontent.com/1325054/80347021-00d49a00-886c-11ea-862b-8cd4ff9b4977.png)

got me thinking: that function is surely useful for the validation of `codecheck.yml`, _should we make this package `Depends: R (>= 4.0.0)` ?_

Note: [In the register I already introduced `assertthat`](https://github.com/codecheckers/register/blob/master/check_register.R#L37) for checks, so this might be a moot point.

**Comment by sje30** [comment]
happy for us to switch to R 4.0.0
and happy to adopt this syntax in the new stopifnot(...) glad to see that become a bit more useful/known.
