### ISSUE TITLE
Where to put the source repo?

### ISSUE THREAD

**Issue by sje30** [codecheckers/codecheck#4]
Currently I see no place  in codecheck.yml for where we should list the URL of the original code repository that we are checking.

how about a new field source: to point to a URL of where the software came from?  Or that might need to be an open string, as sometimes we will need to describe several URLs, one for the code, one for the data, ....

**Comment by nuest** [comment]
You mean in case the codecheck/repo - fork does not point to it anymore?

Would it suffice to record this in the register?

It would be nice to have both links in the Zenodo metadata, I guess.

**Comment by sje30** [comment]
the fork information is still there, but I'm guessing there might be times when the code coming in might not be in github... so having some record of where the code came from would be useful.

**Comment by nuest** [comment]
So that would be an optional field.

Would you expect the author to provide this information, or the codechecker?

**Comment by sje30** [comment]
For a community codecheck, it would probably be the checker providng the info; else it woudl come from the journal/author.

**Comment by nuest** [comment]
If the author provides the information, then the author writes the `codecheck.yml` and submits it, e.g., as supplemental material to a journal submission. I'm wondering how this information is replicated (or should better be part of) the README.

See for an attempt to capture this in the spec: https://github.com/codecheckers/codecheckers.github.io/pull/4

**Comment by nuest** [comment]
We now have a free form field for documenting the source.
